name: Node.js Tests

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
   

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Waiting for Postgres to start
        run: |
          until pg_isready -h postgres -p 5432 -U "postgres"; do
            sleep 1;
          done
      - name: Seed the database
        run: npm run seed
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
